### ISSUE TITLE
"NO VERDICT" instead of "IN QUEUE"

### ISSUE THREAD

**Issue by Rsilnav** [david-perez/uva-stalker#3]
Might be an API issue, but bot is sending "No verdict" while the submission is in queue.

**Comment by david-perez** [comment]
Yeah, the incorrect verdict is being sent by uHunt's API.

Nonetheless, we should not report unjudged submissions and wait until they are off the queue to send the notifications, so 92df34c takes care of that.

Thank you for noticing.
